//widgets/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVp3e6pITNWu73UaJnxTzGfslWd7MCNqM',
    appId: '1:694537516745:web:043559a3d4b12ee7bbff18',
    messagingSenderId: '694537516745',
    projectId: 'tax-calculator-app-69f78',
    authDomain: 'tax-calculator-app-69f78.firebaseapp.com',
    storageBucket: 'tax-calculator-app-69f78.firebasestorage.app',
    measurementId: 'G-G819LDXWFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lSUdG9Pf0lemu_edmbtKJu-InGgbOUY',
    appId: '1:694537516745:android:315601d3ed2b012cbbff18',
    messagingSenderId: '694537516745',
    projectId: 'tax-calculator-app-69f78',
    storageBucket: 'tax-calculator-app-69f78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7CCtyBRIbFp_wl1ELHikIhYw2MCsUYI',
    appId: '1:694537516745:ios:cc5a5e90d4b2e79abbff18',
    messagingSenderId: '694537516745',
    projectId: 'tax-calculator-app-69f78',
    storageBucket: 'tax-calculator-app-69f78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7CCtyBRIbFp_wl1ELHikIhYw2MCsUYI',
    appId: '1:694537516745:ios:cc5a5e90d4b2e79abbff18',
    messagingSenderId: '694537516745',
    projectId: 'tax-calculator-app-69f78',
    storageBucket: 'tax-calculator-app-69f78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVp3e6pITNWu73UaJnxTzGfslWd7MCNqM',
    appId: '1:694537516745:web:0a30bc37a5956eb0bbff18',
    messagingSenderId: '694537516745',
    projectId: 'tax-calculator-app-69f78',
    authDomain: 'tax-calculator-app-69f78.firebaseapp.com',
    storageBucket: 'tax-calculator-app-69f78.firebasestorage.app',
    measurementId: 'G-FP5E13XD5S',
  );
}
